name: Check Plugins Installed

on:
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    strategy:
      matrix:
        plugins:
          - acquia
          - apache
          - backdrop
          - compose
          - dotnet
          - drupal
          - elasticsearch
          - go
          - joomla
          - lagoon
          - lamp
          - laravel
          - lemp
          - mailhog
          - mariadb
          - mean
          - memcached
          - mongo
          - mssql
          - mysql
          - nginx
          - node
          - pantheon
          - php
          - phpmyadmin
          # - platformsh
          - postgres
          - python
          - redis
          - ruby
          - solr
          - symfony
          - tomcat
          - wordpress
          - varnish
        node-version:
          - 'lts/*'

    steps:
      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install docker-compose
        run: |
          REPO="docker/compose"
          LATEST_RELEASE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --silent "https://api.github.com/repos/${REPO}/releases/latest" | jq -r .tag_name)
          sudo curl -L "https://github.com/${REPO}/releases/download/${LATEST_RELEASE}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose && sudo chmod 0755 /usr/local/bin/docker-compose

      # - name: Install via hyperdrive if above is bad
      - name: Disable usage and error reporting
        run: |
          mkdir -p ~/.lando/cache
          echo false > ~/.lando/cache/report_errors
          sed -i "s/report: true.*/report: false/" config.yml
      - name: Package CLI
        run: |
          yarn add --ignore-engines @lando/acquia@^0.5.0 @lando/apache@^0.5.0 @lando/argv@^1.1.0 @lando/backdrop@^0.5.0 @lando/dotnet@^0.5.0 @lando/drupal@^0.5.0 @lando/elasticsearch@^0.5.0 @lando/go@^0.5.0 @lando/joomla@^0.5.0 @lando/lagoon@^0.5.0 @lando/lamp@^0.5.0 @lando/laravel@^0.5.0 @lando/lemp@^0.5.0 @lando/mariadb@^0.5.0 @lando/mean@^0.5.0 @lando/memcached @lando/mongo@^0.5.0 @lando/mssql@^0.5.0 @lando/mysql@^0.5.0 @lando/nginx@^0.5.0 @lando/node@^0.5.0 @lando/pantheon@^0.5.0 @lando/php@^0.5.0 @lando/postgres@^0.5.0 @lando/python@^0.5.0 @lando/redis@^0.5.0 @lando/ruby@^0.5.0 @lando/solr@^0.5.0 @lando/symfony@^0.5.0 @lando/tomcat@^0.5.0 @lando/varnish@^0.5.0 @lando/wordpress@^0.5.0
          yarn build:cli
      - name: Replace source CLI with packaged one
        run: sudo mv ./dist/@lando/cli /usr/local/bin/lando
      - name: Verify we can run the packaged CLI
        run: |
          lando version
          lando config

      # Checks to make sure the plugins listed in the matrix have the right path
      - name: Check if @lando/${{ matrix.plugins }} is installed correctly
        run: |
          lando config --path plugins | grep node_modules/@lando/${{ matrix.plugins }}
